# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: TACogACWrKrB83Mn45P0

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: TACogACWrKrB83Mn45P0
    salt: "generateme"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  padmablog.com:
    env:
      wp_env: production
      db_password: TACogACWrKrB83Mn45P0
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "n9`TQz2IVk@R#;DZdS0?u>s2G<9zlAZ&xm!MYfgXjv3]&,oJy(?p)Bgz72jixv}("
      secure_auth_key: "67alm#Q<LY,VP<}>a#BH!Zuv/j(`ztj=T1ZB{B>f`6)-?u$PPI[44cCH#Nd}L<uO"
      logged_in_key: "Sun@]8tU@P_4n+OD,%!2(H7kT)!)vrsUjw*]ktKV`W&.=<S1gk,%)9^Lc^M1AO$."
      nonce_key: "J[nK1{?:Ej<_1!/O8KDY<`y}[DJ%wOW9Zv.xkcXU2SC+kRweU*?J5)>s]Y=a1s}7"
      auth_salt: "V/o/xv5*6Ewa$=A{au.7hA3O?4T=FzZ4k=G=]m)Myj1.5u3T9M^tPaJR]?#LPdIh"
      secure_auth_salt: "XvUHZZ</xV!Hjdg]f.??,,PqoUcY_9}Kk`.+R-@Ibtj4-trEB>]PN$UnN#z&I;4i"
      logged_in_salt: "qDqe0@|Y!:?+d1[hol[047UTD_y5$ML[A3I6D>0V&!Hu2=MK`8`Eu*U4dm]|Wn:J"
      nonce_salt: "kE!bfv9ZT%KIxr*s?N*ljlCC2LhZ1S{RUf(9Ifi[`*g8C))?E>MuG2xb0|}@P;XP"
  teknovagrant.com:
    env:
      wp_env: production
      db_password: TACogACWrKrB83Mn45P0
      db_prefix: wp_cnfa_
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "A.8&C_Cf}/Q9x1AzN5K-7M)w-y=LrGfu>94a>o_w@j6j.HJC;pKmDF}aRA71f#bV"
      secure_auth_key: "`c$OPi=XQnT_7y-7+aOV-ykL!ucE55GHz(Bc:O-]v|SG$<1+!L)J96Gh/LN2[w%*"
      logged_in_key: "E$KcB;5.e%M+B_%hgj(Cns5B#^c&L=uEmepGe3(}3f8GKQxZy1BhZ|J$}#:Ek)b{"
      nonce_key: "bL_oM}n>z+op{!Wrj[no5ocCE3gc9+L[<M]6sO9Ltr_ehC3S8v6&>8(,uE@L8,wk"
      auth_salt: "cU#U&^-5yL?^vqMCe-Q+jmpcvPILKdYz0H4Cm<,4gLo!d!T^MP}&KOTyw#m1}X-T"
      secure_auth_salt: "<Gt$R?pgmHqV$k3-cN|,-?nqpja${%@XNaa1pbcfhC(J}DXh$1*w^L2>@HnP6v0d"
      logged_in_salt: "(jN4^:|Rb>njiTQPb.,@i23E5twD_PS$_JuDvK6Xm^8.3v^8}:0nj,]6|jY2uZd<"
      nonce_salt: "j_b=6x|jnD)4`jusSJ1-C<^yzb/1^=dJC0T/OJjtzy<k,.3D*JV-i%X0=KMeBRZo"