# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  www.padmablog.com:
    site_hosts:
      - canonical: www.padmablog.com
      - canonical: padmablog.com
    redirects:
      - padmablog.com
    user: deploy
    group: www-data
    local_path: ../padma # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:hitek/personalSites.git # replace with your Git repo URL
    repo_subtree_path: padma # relative path to your Bedrock/WP directory in your repo
    branch: master
    env:
      wp_home: https://www.padmablog.com
    multisite:
      enabled: false
    ssl:
      enabled: false
    cache:
      enabled: false